version: "3.8"

networks:
    saly_network:

services:
    mysql_db:
        image: mysql:8.0
        environment:
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: api
        ports:
            - 3336:3306
        volumes:
            - ./_data/mysql:/var/lib/mysql
        networks:
            - saly_network

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - ./api:/app
        networks:
            - saly_network
        ports:
            - "7070:80"
        environment:
            APP_SLUG: saly-task
            APP_NAME: Saly
            WEB_DOCUMENT_ROOT: /app/public
            DB_DATABASE: api
        depends_on:
            - mysql_db